---
title: Notes for panel session
author: Rhian Davies
---

# Official Statistics and Health: Developing coherent and accessible health statistics: a UK perspective
_Royal Statistical Society 2020 Conference: Panel Session_

## About me

* Data Scientist at [Jumping Rivers](https://www.jumpingrivers.com)
    * Jumping Rivers based in Newcastle, ~7 consultants working remotely
    * Provides training and consultancy
    * Consultancy is a mix of data analysis, statistical modelling and code development & deployment
    * Many different sectors including official statistics, public health, national utilities, financial etc.
* Previously Stats PhD in clustering, data consultancy for the rail industry and internal consultancy at Unilever

## View point

- Understand the users through user personas
- Offer tailored options
- Provide open data and code for the curious user
- Accessiblity (WCAG)

## Questions

> The Inclusive Data Taskforce Implementation Plan (Inclusive Data Principle 8) is about ensuring UK data and evidence are equally accessible to all and talks about ensuring that "language, literacy, format and comprehension are taken into account when presenting analysis and evidence". So, how can we ensure that we communicate statistics in ways that take into account differences in language, literacy, format and comprehension between population groups and communities? 

- Accessible slides (HTML)
- Providing detailed descriptions for plots

> If definitions are not the same at different levels (country, regional, local authorities) how do you best communicate these differences, and, where relevant, approaches that can be taken to making comparisons across the different levels.

> How do you best communicate complex pictures to a wide audience without confusing and overcomplicated explanations, especially as the topics may be emotionally charged or sensitive?

> How do you balance transparent and accurate reporting with accessibility?  

> What does work when communicating health risks and survival to users? What does not?

> Communication (rather than just dissemination) works both ways.  How do you ensure that you are open to communication from users, and responsive to any comments made - and also seen to be responsive?

- Having presentations and reports on a tool like GitHub means there is automatically a place for interested parties to feedback
- I'm a fan of user-driven user-studies throughout the process

## References

- [Writing Alt Text for Data Visualization](https://medium.com/nightingale/writing-alt-text-for-data-visualization-2a218ef43f81)

