---
title: "Notes"
author: "Rhian Davies"
date: "15 October 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
Notes for my talk to DSI students.

## Who am I?

* Data Scientist at parties, statistician at heart :heart:.
* Play up my statistical training. 
* Used to hate statitsics
* Realised it's *useful*
* PhD Clustering of data streams (video, audio, simulated)

### Data Science is *Glamourous*

* Understand how people use deodorant
* When, how many grams, how often?

### Bias

What is bias? 
Sampling? Hurricane katrina - shopping and partying. 
Entrepreenurs - self identified
General pop - not "non"-entrpreneurs
WEIRD - huge bias crisis 
(Western, Educated, from Industrialised, Rich, Democritised countries)

### Transformation

* Data tranformation and cleaning is a huge part of my job.
* Scroll up and down a CSV - ignoring enigne warmup and standard behaviour - looking for anomalies
* Take the engineers brain and build it into my model.


